spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/moviedb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#showSql
logging:
  level:
    com:
      bin:
        app:
          mapper : debug